spring:
  datasource:
    url: jdbc:mysql://47.100.172.22:3306/background?useUnicode=true&charactorEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123
